# Generated by Django 5.0.9 on 2024-10-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_song_title', models.CharField(max_length=200)),
                ('letter_title', models.CharField(max_length=500)),
                ('letter_content', models.TextField()),
                ('write_date', models.DateTimeField()),
            ],
        ),
    ]
