# Generated by Django 5.0.9 on 2024-10-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
