# Generated by Django 5.0.9 on 2024-10-07 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letter_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=200)),
                ('lyricist', models.CharField(max_length=10)),
                ('composer', models.CharField(max_length=10)),
                ('album_title', models.CharField(max_length=100)),
                ('lyrics', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='letter',
            name='letter_song_title',
        ),
        migrations.AddField(
            model_name='letter',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='letters.song'),
        ),
    ]
