# Generated by Django 5.0.9 on 2024-11-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_song_remove_letter_letter_song_title_letter_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='letter',
            name='letter_abstract',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='lyric_love_line',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=50),
        ),
    ]
