# Generated by Django 5.0.9 on 2024-11-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_letter_is_like_letter_letter_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='today_rating',
            field=models.IntegerField(default=0),
        ),
    ]
